<?php

/**
 * Checks if visitor is a bot.
 */
function isBot(): bool
{
    $userAgent = $_SERVER['HTTP_USER_AGENT'] ?? '';
    $bots = [
        "ABCdatos BotLink",
        "Acme.Spider",
        "Ahoy! The Homepage Finder",
        "AhrefsBot",
        "Alkaline",
        "Amazonbot",
        "ananzi",
        "Anthill",
        "Anthropic-ai",
        "Apie",
        "Applebot-Extended",
        "Arale",
        "Araneo",
        "AraybOt",
        "ArchitextSpider",
        "Aretha",
        "ARIADNE",
        "arks",
        "AskJeeves",
        "ASpider (Associative Spider)",
        "ATN Worldwide",
        "Atomz.com Search Robot",
        "AURESYS",
        "BacklinkCrawler",
        "BackRub",
        "Baiduspider",
        "Bay Spider",
        "Big Brother",
        "Bjaaland",
        "BlackWidow",
        "BLEXBot",
        "Die Blinde Kuh",
        "Bloodhound",
        "Borg-Bot",
        "BoxSeaBot",
        "bright.net caching robot",
        "BSpider",
        "Bytespider",
        "CACTVS Chemistry Spider",
        "Calif",
        "Cassandra",
        "Checkbot",
        "ChatGPT-User",
        "ChristCrawler.com",
        "churl",
        "CCCrawler",
        "Cohere-ai",
        "cIeNcIaFiCcIoN.nEt",
        "CMC/0.01",
        "Collective",
        "Combine System",
        "Conceptbot",
        "ConfuzzledBot",
        "CoolBot",
        "CyberSpyder Link Test",
        "CydralSpider",
        "Cyotek WebCopy",
        "DeWeb(c) Katalog/Index",
        "Desert Realm Spider",
        "DienstSpider",
        "Diffbot",
        "Digger",
        "Digital Integrity Robot",
        "Direct Hit Grabber",
        "Discordbot",
        "DNAbot",
        "DotBot",
        "Download Ninja",
        "DownLoad Express",
        "DragonBot",
        "DWCP (Dridus' Web Cataloging Project)",
        "e-collector",
        "EbiNess",
        "EIT Link Verifier Robot",
        "ELFINBOT",
        "Emacs-w3 Search Engine",
        "Esther",
        "esculapio",
        "Evliya Celebi",
        "FacebookBot",
        "facebookexternalhit",
        "FastCrawler",
        "Felix IDE",
        "FetchRover",
        "fido",
        "Fish search",
        "Fluid Dynamics Search Engine robot",
        "Fouineur",
        "Freecrawl",
        "FunnelWeb",
        "gammaSpider, FocusedCrawler",
        "Gazz",
        "GCreep",
        "GetBot",
        "GetterroboPlus Puu",
        "GetURL",
        "Golem",
        "Google-Extended",
        "GoogleOther",
        "Googlebot",
        "GPTBot",
        "Grapnel/0.01 Experiment",
        "Griffon",
        "Grub-client",
        "Gromit",
        "Gulper Bot",
        "HamBot",
        "Harvest",
        "havIndex",
        "Helium Scraper",
        "HI (HTML Index) Search",
        "HKU WWW Octopus",
        "Hometown Spider Pro",
        "HTTrack",
        "HTMLgobble",
        "Hyper-Decontextualizer",
        "ia_archiver",
        "iajaBot",
        "IBM_Planetwide",
        "Imagelock",
        "image.kapsi.net",
        "IncyWincy",
        "Ingrid",
        "Informant",
        "InfoSeek Robot 1.0",
        "Infoseek Sidewinder",
        "InfoSpiders",
        "Inspector Web",
        "IntelliAgent",
        "Internet Cruiser Robot",
        "Internet Shinchakubin",
        "I, Robot",
        "Iron33",
        "Israeli-search",
        "Javabee",
        "JBot Java Web Robot",
        "JCrawler",
        "Jeeves",
        "JoBo Java Web Robot",
        "Jobot",
        "JoeBot",
        "JumpStation",
        "Katipo",
        "KDD-Explorer",
        "KIT-Fireball",
        "Kilroy",
        "KO_Yappo_Robot",
        "LabelGrabber",
        "larbin",
        "legs",
        "libwww",
        "LinkedInBot",
        "Linkdexbot",
        "LinkScan",
        "LinkValidator",
        "LinkWalker",
        "Lockon",
        "logo.gif Crawler",
        "Lycos",
        "Mac WWWWorm",
        "Magpie",
        "Magpie-crawler",
        "marvin/infoseek",
        "Mattie",
        "MediaFox",
        "MerzScope",
        "MindCrawler",
        "MJ12bot",
        "mnoGoSearch search engine software",
        "moget",
        "MOMspider",
        "Monster",
        "Motor",
        "MSNBot",
        "Muncher",
        "Muninn",
        "Muscat Ferret",
        "Mwd.Search",
        "NDSpider",
        "Nederland.zoek",
        "NetCarta WebMap Engine",
        "NetMechanic",
        "NetScoop",
        "newscan-online",
        "NHSE Web Forager",
        "Nomad",
        "Northern Light Gulliver",
        "The NorthStar Robot",
        "nzexplorer",
        "ObjectsSearch",
        "Occam",
        "Offline Explorer",
        "OgimgiliBot",
        "OmigiliBot",
        "OntoSpider",
        "Open Text Index Robot",
        "Openfind data gatherer",
        "PageBoy",
        "Pack Rat",
        "ParaSite",
        "Panscient.com",
        "Patric",
        "Pegasus",
        "PerlCrawler 1.0",
        "PerplexityBot",
        "PetalBot",
        "Phantom",
        "PhpDig",
        "PiltdownMan",
        "Pimptrain.com's robot",
        "Pinterestbot",
        "Pioneer",
        "PlumtreeWebAccessor",
        "Poppi",
        "Popular Iconoclast",
        "Portal Juice Spider",
        "PortalB Spider",
        "psbot",
        "Qwantify",
        "Raven Search",
        "RBSE Spider",
        "Resume Robot",
        "RixBot",
        "Road Runner: The ImageScape Robot",
        "RoadHouse Crawling System",
        "Robbie the Robot",
        "RoboCrawl Spider",
        "RoboFox",
        "Robozilla",
        "Roverbot",
        "RuLeS",
        "SafetyNet Robot",
        "Scooter",
        "Search.Aus-AU.COM",
        "SearchmetricsBot",
        "SearchProcess",
        "SEOkicks-Robot",
        "SemrushBot",
        "Senrigan",
        "SerpstatBot",
        "SG-Scout",
        "ShagSeeker",
        "Shai'Hulud",
        "Sift",
        "Simmany Robot Ver1.0",
        "Site Searcher",
        "Site Valet",
        "SiteSnagger",
        "SiteTech-Rover",
        "SkypeUriPreview",
        "Slackbot",
        "SLCrawler",
        "Snooper",
        "Sogou Spider",
        "Solbot",
        "Spanner",
        "Speedy Spider",
        "SpiderBot",
        "spider_monkey",
        "Spiderline Crawler",
        "SpiderMan",
        "SpiderView(tm)",
        "Spry Wizard Robot",
        "Suke",
        "Sven",
        "Sygol",
        "TACH Black Widow",
        "Tarantula",
        "tarspider",
        "Tcl W3 Robot",
        "TechBOT",
        "TelegramBot",
        "TeomaTechnologies",
        "Templeton",
        "TITAN",
        "TitIn",
        "The Jubii Indexing Robot",
        "The NWI Robot",
        "The Peregrinator",
        "The Python Robot",
        "The TkWWW Robot",
        "The Web Moose",
        "the World Wide Web Wanderer",
        "The Web Wombat",
        "Twitterbot",
        "TurnitinBot",
        "UCSD Crawl",
        "UdmSearch",
        "UptimeBot",
        "URL Check",
        "URL Spider Pro",
        "Valkyrie",
        "Verticrawl",
        "Victoria",
        "vision-search",
        "void-bot",
        "Voyager",
        "VWbot",
        "W3M2",
        "WallPaper (alias crawlpaper)",
        "Walhello appie",
        "WebBandit Web Spider",
        "WebCatcher",
        "WebCopy",
        "WebCopier",
        "webfetcher",
        "Webfoot Robot",
        "Webgobble",
        "Webinator",
        "Weblayers",
        "WebLinker",
        "Weblog Monitor",
        "WebMirror",
        "WebQuest",
        "WebReaper",
        "Websnarf",
        "WebSpider",
        "WebStolperer",
        "WebStripper",
        "WebVac",
        "WebWalker",
        "WebWatch",
        "WebZIP",
        "WebZinger",
        "WhatUseek Winona",
        "WhoWhere Robot",
        "Wired Digital",
        "Wget",
        "w3mir",
        "WWWC Ver 0.2.5",
        "Xenu",
        "XGET",
        "XYLEME Robot",
        "YandexBot",
        "Yeti",
        "YoudaoBot",
        "ZyBORG"
    ];

    foreach ($bots as $bot) {
        if (stripos($userAgent, $bot) !== false) {
            return true;
        }
    }
    return false;
}
